version: '3'

services:
  gsrs-backend:
    container_name: gsrs-backend
    build:
      context: .
      target: development
    image: gsrs-backend
    restart: on-failure
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    environment:
      - MODE=DEV
      # - CLIENT_URL=http://localhost:8080
      - CLIENT_URL=http://gsrs.loi-tra
      - POSTGRES_HOST=gsrs-db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - gsrs-db
    tty: true
    stdin_open: true

  gsrs-db:
    image: postgres
    container_name: gsrs-db
    restart: always
    env_file:
      - .env # to get the following env vars: POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB
    ports:
      - "${POSTGRES_PORT-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    #   - ./data/postgres:/data/postgres (?)

networks:
  default:
    name: gsrs-local-net
    driver: bridge

volumes:
  postgres-data: